; exact pic bank per internal id, read by UncompressMonSprite (home/pics.asm)
; generated from each species base_stats front-pic pointer
SECTION "Pic Banks", ROMX
EXPORT MonsterPicBanks
MonsterPicBanks:
	db 0 ; NO_MON
	db BANK(RhydonPicFront) ; RHYDON
	db BANK(KangaskhanPicFront) ; KANGASKHAN
	db BANK(NidoranMPicFront) ; NIDORAN_M
	db BANK(ClefairyPicFront) ; CLEFAIRY
	db BANK(SpearowPicFront) ; SPEAROW
	db BANK(VoltorbPicFront) ; VOLTORB
	db BANK(NidokingPicFront) ; NIDOKING
	db BANK(SlowbroPicFront) ; SLOWBRO
	db BANK(IvysaurPicFront) ; IVYSAUR
	db BANK(ExeggutorPicFront) ; EXEGGUTOR
	db BANK(LickitungPicFront) ; LICKITUNG
	db BANK(ExeggcutePicFront) ; EXEGGCUTE
	db BANK(GrimerPicFront) ; GRIMER
	db BANK(GengarPicFront) ; GENGAR
	db BANK(NidoranFPicFront) ; NIDORAN_F
	db BANK(NidoqueenPicFront) ; NIDOQUEEN
	db BANK(CubonePicFront) ; CUBONE
	db BANK(RhyhornPicFront) ; RHYHORN
	db BANK(LaprasPicFront) ; LAPRAS
	db BANK(ArcaninePicFront) ; ARCANINE
	db BANK(MewPicFront) ; MEW
	db BANK(GyaradosPicFront) ; GYARADOS
	db BANK(ShellderPicFront) ; SHELLDER
	db BANK(TentacoolPicFront) ; TENTACOOL
	db BANK(GastlyPicFront) ; GASTLY
	db BANK(ScytherPicFront) ; SCYTHER
	db BANK(StaryuPicFront) ; STARYU
	db BANK(BlastoisePicFront) ; BLASTOISE
	db BANK(PinsirPicFront) ; PINSIR
	db BANK(TangelaPicFront) ; TANGELA
	db BANK(OnixPicFront) ; PETIROC
	db BANK(DodrioPicFront) ; AILESOR
	db BANK(GrowlithePicFront) ; GROWLITHE
	db BANK(OnixPicFront) ; ONIX
	db BANK(FearowPicFront) ; FEAROW
	db BANK(PidgeyPicFront) ; PIDGEY
	db BANK(SlowpokePicFront) ; SLOWPOKE
	db BANK(KadabraPicFront) ; KADABRA
	db BANK(GravelerPicFront) ; GRAVELER
	db BANK(ChanseyPicFront) ; CHANSEY
	db BANK(MachokePicFront) ; MACHOKE
	db BANK(MrMimePicFront) ; MR_MIME
	db BANK(HitmonleePicFront) ; HITMONLEE
	db BANK(HitmonchanPicFront) ; HITMONCHAN
	db BANK(ArbokPicFront) ; ARBOK
	db BANK(ParasectPicFront) ; PARASECT
	db BANK(PsyduckPicFront) ; PSYDUCK
	db BANK(DrowzeePicFront) ; DROWZEE
	db BANK(GolemPicFront) ; GOLEM
	db BANK(BeedrillPicFront) ; BUGGAIE
	db BANK(MagmarPicFront) ; MAGMAR
	db BANK(VileplumePicFront) ; FLORALYS
	db BANK(ElectabuzzPicFront) ; ELECTABUZZ
	db BANK(MagnetonPicFront) ; MAGNETON
	db BANK(KoffingPicFront) ; KOFFING
	db BANK(PoliwrathPicFront) ; AQUAJET
	db BANK(MankeyPicFront) ; MANKEY
	db BANK(SeelPicFront) ; SEEL
	db BANK(DiglettPicFront) ; DIGLETT
	db BANK(TaurosPicFront) ; TAUROS
	db BANK(MagnetonPicFront) ; VOLTOUR
	db BANK(MrMimePicFront) ; PSYMINI
	db BANK(DewgongPicFront) ; GLACIETTE
	db BANK(FarfetchdPicFront) ; FARFETCHD
	db BANK(VenonatPicFront) ; VENONAT
	db BANK(DragonitePicFront) ; DRAGONITE
	db BANK(WeepinbellPicFront) ; FLORAQUE
	db BANK(GolemPicFront) ; ROCBOUL
	db BANK(ArbokPicFront) ; SERPICOL
	db BANK(DoduoPicFront) ; DODUO
	db BANK(PoliwagPicFront) ; POLIWAG
	db BANK(JynxPicFront) ; JYNX
	db BANK(MoltresPicFront) ; MOLTRES
	db BANK(ArticunoPicFront) ; ARTICUNO
	db BANK(ZapdosPicFront) ; ZAPDOS
	db BANK(DittoPicFront) ; DITTO
	db BANK(MeowthPicFront) ; MEOWTH
	db BANK(KrabbyPicFront) ; KRABBY
	db BANK(GolbatPicFront) ; CHAUVESPI
	db BANK(DugtrioPicFront) ; TERREUX
	db BANK(SlowbroPicFront) ; MARAISOR
	db BANK(VulpixPicFront) ; VULPIX
	db BANK(NinetalesPicFront) ; NINETALES
	db BANK(PikachuPicFront) ; PIKACHU
	db BANK(RaichuPicFront) ; RAICHU
	db BANK(PidgeotPicFront) ; OISEAULO
	db BANK(KinglerPicFront) ; CRABEAU
	db BANK(DratiniPicFront) ; DRATINI
	db BANK(DragonairPicFront) ; DRAGONAIR
	db BANK(KabutoPicFront) ; KABUTO
	db BANK(KabutopsPicFront) ; KABUTOPS
	db BANK(HorseaPicFront) ; HORSEA
	db BANK(SeadraPicFront) ; SEADRA
	db BANK(HaunterPicFront) ; FANTOMIN
	db BANK(RaichuPicFront) ; ELECTROX
	db BANK(SandshrewPicFront) ; SANDSHREW
	db BANK(SandslashPicFront) ; SANDSLASH
	db BANK(OmanytePicFront) ; OMANYTE
	db BANK(OmastarPicFront) ; OMASTAR
	db BANK(JigglypuffPicFront) ; JIGGLYPUFF
	db BANK(WigglytuffPicFront) ; WIGGLYTUFF
	db BANK(EeveePicFront) ; EEVEE
	db BANK(FlareonPicFront) ; FLAREON
	db BANK(JolteonPicFront) ; JOLTEON
	db BANK(VaporeonPicFront) ; VAPOREON
	db BANK(MachopPicFront) ; MACHOP
	db BANK(ZubatPicFront) ; ZUBAT
	db BANK(EkansPicFront) ; EKANS
	db BANK(ParasPicFront) ; PARAS
	db BANK(PoliwhirlPicFront) ; POLIWHIRL
	db BANK(PoliwrathPicFront) ; POLIWRATH
	db BANK(WeedlePicFront) ; WEEDLE
	db BANK(KakunaPicFront) ; KAKUNA
	db BANK(BeedrillPicFront) ; BEEDRILL
	db BANK(GrowlithePicFront) ; FLAMELET
	db BANK(DodrioPicFront) ; DODRIO
	db BANK(PrimeapePicFront) ; PRIMEAPE
	db BANK(DugtrioPicFront) ; DUGTRIO
	db BANK(VenomothPicFront) ; VENOMOTH
	db BANK(DewgongPicFront) ; DEWGONG
	db BANK(AerodactylPicFront) ; DRAGONET
	db BANK(CaterpiePicFront) ; CATERPIE
	db BANK(MetapodPicFront) ; METAPOD
	db BANK(ButterfreePicFront) ; BUTTERFREE
	db BANK(MachampPicFront) ; MACHAMP
	db BANK(GolduckPicFront) ; GOLDUCK
	db BANK(HypnoPicFront) ; HYPNO
	db BANK(GolbatPicFront) ; GOLBAT
	db BANK(MewtwoPicFront) ; MEWTWO
	db BANK(SnorlaxPicFront) ; SNORLAX
	db BANK(MagikarpPicFront) ; MAGIKARP
	db BANK(MukPicFront) ; MUK
	db BANK(KinglerPicFront) ; KINGLER
	db BANK(CloysterPicFront) ; CLOYSTER
	db BANK(ElectrodePicFront) ; ELECTRODE
	db BANK(ClefablePicFront) ; CLEFABLE
	db BANK(WeezingPicFront) ; WEEZING
	db BANK(PersianPicFront) ; PERSIAN
	db BANK(MarowakPicFront) ; MAROWAK
	db BANK(AlakazamPicFront) ; MENTALIS
	db BANK(HaunterPicFront) ; HAUNTER
	db BANK(AbraPicFront) ; ABRA
	db BANK(AlakazamPicFront) ; ALAKAZAM
	db BANK(PidgeottoPicFront) ; PIDGEOTTO
	db BANK(PidgeotPicFront) ; PIDGEOT
	db BANK(StarmiePicFront) ; STARMIE
	db BANK(BulbasaurPicFront) ; BULBASAUR
	db BANK(VenusaurPicFront) ; VENUSAUR
	db BANK(TentacruelPicFront) ; TENTACRUEL
	db BANK(DragonitePicFront) ; DRACOZELLE
	db BANK(GoldeenPicFront) ; GOLDEEN
	db BANK(SeakingPicFront) ; SEAKING
	db BANK(GengarPicFront) ; SPECTRELA
	db BANK(NidokingPicFront) ; VENOMBRU
	db BANK(RhydonPicFront) ; TERRAKOR
	db BANK(JolteonPicFront) ; FULGURAX
	db BANK(PonytaPicFront) ; PONYTA
	db BANK(RapidashPicFront) ; RAPIDASH
	db BANK(RattataPicFront) ; RATTATA
	db BANK(RaticatePicFront) ; RATICATE
	db BANK(NidorinoPicFront) ; NIDORINO
	db BANK(NidorinaPicFront) ; NIDORINA
	db BANK(GeodudePicFront) ; GEODUDE
	db BANK(PorygonPicFront) ; PORYGON
	db BANK(AerodactylPicFront) ; AERODACTYL
	db BANK(LaprasPicFront) ; GIVRALP
	db BANK(MagnemitePicFront) ; MAGNEMITE
	db BANK(ArcaninePicFront) ; PYROFELIS
	db BANK(HypnoPicFront) ; OBSCURAX
	db BANK(CharmanderPicFront) ; CHARMANDER
	db BANK(SquirtlePicFront) ; SQUIRTLE
	db BANK(CharmeleonPicFront) ; CHARMELEON
	db BANK(WartortlePicFront) ; WARTORTLE
	db BANK(CharizardPicFront) ; CHARIZARD
	db BANK(FearowPicFront) ; CRAMORIL
	db BANK(FossilKabutopsPic) ; FOSSIL_KABUTOPS
	db BANK(FossilAerodactylPic) ; FOSSIL_AERODACTYL
	db BANK(GhostPic) ; MON_GHOST
	db BANK(OddishPicFront) ; ODDISH
	db BANK(GloomPicFront) ; GLOOM
	db BANK(VileplumePicFront) ; VILEPLUME
	db BANK(BellsproutPicFront) ; BELLSPROUT
	db BANK(WeepinbellPicFront) ; WEEPINBELL
	db BANK(VictreebelPicFront) ; VICTREEBEL
