#!/usr/bin/env python3
"""Regenerate gfx/pic_banks.asm (MonsterPicBanks).

One entry per internal id: the bank of the *PicFront label the species'
BaseStats pointer references. Indexed by internal id (const_skip-aware),
matching UncompressMonSprite's lookup.

Run manually or via `make registry`; verified by tools/check_rom.py.
"""
import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

SPECIALS = {
    'NO_MON': '0',
    'MEW': 'BANK(MewPicFront)',
    'FOSSIL_KABUTOPS': 'BANK(FossilKabutopsPic)',
    'FOSSIL_AERODACTYL': 'BANK(FossilAerodactylPic)',
    'MON_GHOST': 'BANK(GhostPic)',
}


def internal_ids():
    ids, val = {}, 0
    for line in (ROOT / 'constants/pokemon_constants.asm').read_text().splitlines():
        if re.match(r'\s*const_skip\b', line):
            val += 1
            continue
        m = re.match(r'\s*const (\w+)', line)
        if m:
            ids[m.group(1)] = val
            val += 1
    return ids


def base_stats_source(const):
    for stem in (const.lower(), const.lower().replace('_', '')):
        p = ROOT / 'data/pokemon/base_stats' / f'{stem}.asm'
        if p.exists():
            return p.read_text()
    return None


def main():
    ids = internal_ids()
    max_id = max(ids.values())

    # species with their own pic: labels in gfx/pics.asm, in id order
    pic_lines = (ROOT / 'gfx/pics.asm').read_text()
    labels = re.findall(r'^(\w+)PicFront::', pic_lines, re.M)
    core = sorted((i, c) for c, i in ids.items()
                  if c not in SPECIALS and (i, c))
    # species without a pics.asm entry borrow via base_stats (NERIS, etc.)
    own = {}
    borrows = {}
    k = 0
    for i, c in core:
        src = base_stats_source(c)
        m = re.search(r'dw (\w+)PicFront, (\w+)PicBack', src or '')
        if not m:
            continue
        # match against the next pics.asm label: same species?
        if k < len(labels) and labels[k].lower().replace('_', '') == \
                c.lower().replace('_', ''):
            own[i] = labels[k]
            k += 1
        else:
            borrows[i] = m.group(1)
    if k != len(labels):
        raise SystemExit(
            f'pics.asm order mismatch: {len(labels)} labels but {k} matched')

    out = [
        '; exact pic bank per internal id, read by UncompressMonSprite',
        '; (home/pics.asm). GENERATED by tools/gen_pic_banks.py.',
        'SECTION "Pic Banks", ROMX',
        'EXPORT MonsterPicBanks',
        'MonsterPicBanks:',
    ]
    for i in range(max_id + 1):
        c = next((c for cc, i2 in ids.items() for i2 in [i] if False), None)
        c = next((cc for cc, ii in ids.items() if ii == i), None)
        if c is None:
            out.append(f'\tdb 0 ; unused id {i:02X}')
        elif c in SPECIALS:
            out.append(f'\tdb {SPECIALS[c]} ; {c}')
        elif i in borrows:
            out.append(f'\tdb BANK({borrows[i]}PicFront) ; {c}')
        else:
            out.append(f'\tdb BANK({own[i]}PicFront) ; {c}')
    out.append(
        f'assert (@ - MonsterPicBanks) == {max_id + 1}, '
        f'"MonsterPicBanks must have one entry per internal id ({max_id + 1})"')
    (ROOT / 'gfx/pic_banks.asm').write_text('\n'.join(out) + '\n')
    print(f'gfx/pic_banks.asm regenerated: {max_id + 1} entries '
          f'({len(own)} own pics, {len(borrows)} borrows)')


if __name__ == '__main__':
    main()