_VermilionGymLTSurgePreBattleText::
	text "He, petit!"
	line "Qu'est-ce que"
	cont "tu fais ici?"
	para "Tu ne vivras"
	line "pas longtemps"
	cont "au combat! Ca,"
	cont "c'est sur!"
	para "Je te le dis,"
	line "les #MON"
	cont "electriques m'ont"
	cont "sauve pendant"
	cont "la guerre!"
	para "Ils ont paralyse"
	line "mes ennemis!"
	para "Je vais faire"
	line "pareil avec toi!"
	done
